linters:
  rubocop:
    display_cop_names: true
<<<<<<< HEAD
    # indicate where is the config file for stylelint
    config: './rubocop.yml'

# add the files here you want to be ignored by stylelint
=======
>>>>>>> e38a5825522a389c3094556496f7ef80bf94bf73
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"